197_Env_Test:
  197_token: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2tleSI6IjgyODk2MjllLWRjMTItNGY0My1hMWMxLWQzOTBlMmJiNDE1OCIsInVzZXJfaWQiOjE2MywidXNlcm5hbWUiOiIxNTAxMzczNDIwOCJ9.NukIXOGcpX19B_BUHFrk3Dp30Z6hs2uDiyRYq0fiPZ4w8HjdBhF7cG8e-AuyIUVvWBvqX-EMB8t5lTmX5JZAZA
  Interface_Api_Host: http://192.168.3.197:8080/plm/
new_plate:
  access_token: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2tleSI6IjM2NmJkMzliLWQwOGYtNDMwMy1hMjRmLWE1ZDM5Yzg4YzI5MyIsInVzZXJfaWQiOjE1OSwidXNlcm5hbWUiOiJodXprIn0.663Ip5ceELkMWQzRWkRUMnOUuzZZkutvjVQWISJnYDljcPaAOOXKM2C4ccptVZnVAsJLHpdInQ1NM5wIGh_pOw
old_platform:
  company: just seems tenantId
  token: old_token_eyJ0eXA
title: 'Write and maintain by __Author__: HuZk'
