197_Env_Test:
  197_token: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2tleSI6IjhhYTVmY2JmLTg0NjUtNDliOS05MTc4LWY3MTFmODUxMTQ3YyIsInVzZXJfaWQiOjE2MywidXNlcm5hbWUiOiIxNTAxMzczNDIwOCJ9.LL3FpVVaJmAp1ZQJScMhQx-FmyNFoh-daVyLrG98dAFqZ-ZZnYkf0O2yXH2QdQzYh9TPz0SkRVXonkLeHJ62Tg
  Interface_Api_Host: http://192.168.3.197:8080/plm/
new_plate:
  access_token: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2tleSI6IjdkODU4ZTE0LTAzMTQtNDZlZS04MTI5LTVkYjQ1ZGRlNTk5YSIsInVzZXJfaWQiOjE1OSwidXNlcm5hbWUiOiJodXprIn0.xFAqjD7bsS6433uUM4wNXshg__u-lM6ntPmogynS5ZxqboOLaZ-rlcdbkPHtWJpoXNZKFDODa4i98urjPrKjeg
old_platform:
  company: just seems tenantId
  token: old_token_eyJ0eXA
title: 'Write and maintain by __Author__: HuZk'
